### ISSUE TITLE
window is not defined, document is not defined

### ISSUE THREAD

**Issue by ocramot** [murrayju/xslt#12]
I tried using xslt from npm, version 0.8.0 (0.8.1 seems still not available at this time on npm), and I got this error:
```
ReferenceError: window is not defined
    at C:\myDirectory\node_modules\xslt\dist\xslt.min.js:3:1470
    at z.xmlNode (C:\myDirectory\node_modules\xslt\dist\xslt.min.js:3:302)
    at Object.<anonymous> (C:\myDirectory\node_modules\xslt\dist\xslt.min.js:3:328)
    at Object.<anonymous> (C:\myDirectory\node_modules\xslt\dist\xslt.min.js:3:7035)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\myDirectory\xsltCaller.js:17:12)
```
This happens when I call `require("xslt")`;

I've seen that this error has been fixed in 0.8.1, so I tried to use that. Then I got this error:

```
ReferenceError: document is not defined
    at E (C:\myDirectory\node_modules\xslt\dist\xslt.min.js:3:2148)
    at N (C:\myDirectory\node_modules\xslt\dist\xslt.min.js:3:2380)
    at S (C:\myDirectory\node_modules\xslt\dist\xslt.min.js:3:2609)
    at t (C:\myDirectory\node_modules\xslt\dist\xslt.min.js:3:6049)
    at generateVideoMetadataXml (C:\myDirectory\xsltCaller.js:956:11)
```

This happens when I call the function `xslt(input, xsl, options);`

Actually, maybe it's just me, since `window` and `document` are two DOM-related entities, and they are usually used in a browser; is this npm module supposed to be used server-side?

**Comment by ocramot** [comment]
Answered by myself, I read it better and I saw this is supposed to work only on browser. Sorry, I read 'npm' and I misunderstood.
